--- arch/arm64/boot/dts/Makefile
+++ arch/arm64/boot/dts/Makefile
@@ -1,12 +1,12 @@
 # SPDX-License-Identifier: GPL-2.0
-dtb-y += exynos/exynos9810-crownlte_eur_open_23.dtb
 dtb-y += exynos/exynos9810-crownlte_eur_open_21.dtb
-dtb-y += exynos/exynos9810-crownlte_eur_open_17.dtb
-dtb-y += exynos/exynos9810-crownlte_eur_open_26.dtb
-dtb-y += exynos/exynos9810-crownlte_eur_open_18.dtb
 dtb-y += exynos/exynos9810-crownlte_eur_open_25.dtb
+dtb-y += exynos/exynos9810-crownlte_eur_open_17.dtb
 dtb-y += exynos/exynos9810-crownlte_eur_open_24.dtb
 dtb-y += exynos/exynos9810-crownlte_eur_open_19.dtb
+dtb-y += exynos/exynos9810-crownlte_eur_open_23.dtb
+dtb-y += exynos/exynos9810-crownlte_eur_open_26.dtb
+dtb-y += exynos/exynos9810-crownlte_eur_open_18.dtb
 
 targets += dtbs
 DTB_LIST  := $(dtb-y) $(dtbo-y)
